### ISSUE TITLE
Fix Twister Algorithm to usable state

### ISSUE THREAD

**Issue by Skijetler** [YanaGlad/FlashProject#14]
# Create 2 functions : 
**_int_ generate_random_seed(), _byte_ generate_binary_sequence(int seed)**
### _int_ generate_random_seed()
generate a random number, which we will be use as seed
### _byte_ generate_binary_sequence(int seed)
if **RNG** output < **N_max** (**N_max** - max number that can be generated) generate _01010101_, else _10101010_

**Comment by g2px1** [comment]
https://ru.stackoverflow.com/questions/926294/non-constant-expression-cannot-be-narrowed-from-type-int-to-stdbyte
